/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IToasterPoolDeployer,
  IToasterPoolDeployerInterface,
} from "../../../contracts/interfaces/IToasterPoolDeployer";

const _abi = [
  {
    inputs: [],
    name: "parameters",
    outputs: [
      {
        internalType: "address",
        name: "factory",
        type: "address",
      },
      {
        internalType: "address",
        name: "pool",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IToasterPoolDeployer__factory {
  static readonly abi = _abi;
  static createInterface(): IToasterPoolDeployerInterface {
    return new utils.Interface(_abi) as IToasterPoolDeployerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IToasterPoolDeployer {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IToasterPoolDeployer;
  }
}
