/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IToasterRouter,
  IToasterRouterInterface,
} from "../../../contracts/interfaces/IToasterRouter";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "pool",
        type: "address",
      },
    ],
    name: "addNewToaster",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IToasterRouter__factory {
  static readonly abi = _abi;
  static createInterface(): IToasterRouterInterface {
    return new utils.Interface(_abi) as IToasterRouterInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IToasterRouter {
    return new Contract(address, _abi, signerOrProvider) as IToasterRouter;
  }
}
